### ISSUE TITLE
adding PC feature view for resorted units

### ISSUE THREAD

**Issue by jeongjunjjkim** [JonathanAMichaels/PixelProcessingPipeline#4]
Is there an added functionality to add PC feature view for resorter? This is particularly useful for splitting overmerged units after resorting.

**Comment by smarkoco** [comment]
This repo is under active development, and the functionality to view outputted merge results in Phy is actually a new feature. You raise a good point, and I'm sure we will address this at some point (in addition to the currently missing Amplitude View), but right now (at least for me) efforts are going into improving the quality of the resorting, to try to increase sensitivity and precision for each purported neuron.

I'll keep your comment in mind once I get a chance to look at that aspect. Thanks for your input!

**Comment by smarkoco** [comment]
Sorry, was this question about sorting motor units or sorting neurons in the brain?

**Comment by jeongjunjjkim** [comment]
This is a question about sorting motor units - fyi I was one of the authors on the sober lab preprint (sober lab emgs). I have an example where even in intermediate merge, the resorter merges two units of similar looking waveform, but clearly 2 different units (based on amplitude and firing patterns).

**Comment by smarkoco** [comment]
Oh okay, nice to meet you! (virtually hah)

I see.. do you mind sending some example screenshots/etc?

In the pykilosort configuration file (`Kilosort_config_3.m`) you can adjust amplitude flexibility by changing the first and second amplitudes to be the same value (or close to the same value):
https://github.com/JonathanAMichaels/PixelProcessingPipeline/blob/c12209ae4cbf6e7bcf704243557ed68184822d6d/sorting/Kilosort_config_3.m#L13

You could also try increasing the amplitude penalty:
https://github.com/JonathanAMichaels/PixelProcessingPipeline/blob/c12209ae4cbf6e7bcf704243557ed68184822d6d/sorting/Kilosort_config_3.m#L16

**Comment by smarkoco** [comment]
Sorry, ignore the first code line I sent. The below configuration file is higher-level and should override that config:
https://github.com/JonathanAMichaels/PixelProcessingPipeline/blob/c12209ae4cbf6e7bcf704243557ed68184822d6d/sorting/Kilosort_run_myo_3.m#L25

The amplitude penalty should still work, right @JonathanAMichaels ?

**Comment by smarkoco** [comment]
I believe the `Kilosort_config_3.m` is intended to be used as a default across both neural and MU sorting, while the `Kilosort_run_myo_3.m` file is intended to override the default settings specifically for motor units, but looking at it now, those two configs should likely be combined into one :thinking:

**Comment by JonathanAMichaels** [comment]
For myomatrix data Kilosort_run_myo_3 is used, and this pulls config defaults from Kilsoort_config_3. If you want to change anything, you can do it in Kilosort_run_myo_3

**Comment by jeongjunjjkim** [comment]
I'll send some examples of overmerging later this week.
FYI the issue is not with initial Kilosort parameters as 2 separate units are initially detected correctly. The issue is the resorter that merges the 2 units together.

**Comment by jeongjunjjkim** [comment]
Example of overmerging - 2 units merged by resorter into 1 unit.
![phy_screenshot_20230328144851_TraceView](https://user-images.githubusercontent.com/9920532/228339242-66d35981-bdc0-4e91-93d4-06b280801b8b.png)
![phy_screenshot_20230328145303_TraceView](https://user-images.githubusercontent.com/9920532/228339244-221e0a5b-6998-453e-bd31-c265616d7e3e.png)

**Comment by smarkoco** [comment]
Hey @jeongjunjjkim , just to let you know, as of [this commit](https://github.com/JonathanAMichaels/PixelProcessingPipeline/pull/7), the pipeline now allows extracting the waveforms necessary to produce the Phy FeatureView!

**Comment by jeongjunjjkim** [comment]
@smarkoco thanks for the update - however, I was trying this out today, but apparently phy states "could not create view FeatureView" in the gui.

**Comment by smarkoco** [comment]
Wow that's weird, it works on my end :thinking: 

Do you see an output like below when you run either `-myo_sort` or `-myo_post`?
The loading bar should appear, and indicates it succesfully ran `phy extract-waveforms params.py`, as described is this [separate git issue](https://github.com/cortex-lab/phy/issues/1145#issuecomment-1094718768)

![image](https://user-images.githubusercontent.com/53878603/230452577-fea28bd8-e72e-49bd-8c21-5bf4d646296f.png)

**Comment by smarkoco** [comment]
Also, did you freshly clone the repository? Or run `git pull`?

Alternatively, you can try running the `phy extract-waveforms params.py` command in the appropriate folder (e.g. `sorted0` or `final_merge`) in order to try extracting the waveforms yourself. This could help rule out a problem with your phy installation or something

Also, if you have time to checkout the latest Readme.md (front page of Github repo), we've recently added a few new command options which allow changing config files directly in the same terminal window, quickly with `nano`

**Comment by jeongjunjjkim** [comment]
Yes the phy extract-waveforms param.py works! fyi I was using the myomatric_call matlab script to resort kilosort output, rather than running the whole pipeline from python
